---
- name: Create directory ~/.local/bin/
  file:
    path: "{{ ansible_env.HOME }}/.local/bin"
    state: directory
    mode: "0755"

- include_tasks: mac.yml
  when: ansible_os_family == "Darwin"

- include_tasks: debian.yml
  when: ansible_os_family == "Debian"

- name: Install linters and formatters with npm
  shell: "npm install -g {{ item }}"
  loop:
    - eslint_d
    - prettier
  become: true
  changed_when: true

- name: Install stylua from GitHub releases
  unarchive:
    src: "https://github.com/JohnnyMorganz/StyLua/releases/download/v0.13.1/stylua-{{ 'macos' if ansible_facts['os_family'] == 'Darwin' else 'linux' }}.zip"
    dest: "~/.local/bin"
    mode: "u+x"
    remote_src: true
