---
- name: Create directory ~/.local/bin/
  file:
    path: "{{ ansible_env.HOME }}/.local/bin"
    state: directory

- include_tasks: mac.yml
  when: ansible_os_family == "Darwin"

- include_tasks: debian.yml
  when: ansible_os_family == "Debian"

- name: Install linters and formatters with npm
  shell: |
    if [ -x "$(command -v npm)" ]; then
      npm install -g {{ item }}
    elif [ -x "$(command -v pnpm)" ]; then
      pnpm add -g {{ item }}
    fi
  loop:
    - eslint_d
    - prettier
  register: npm_install_efm
  changed_when: "'up to date' not in npm_install_efm.stdout and 'added' in npm_install_efm.stdout"
  become: "{{ ansible_os_family == 'Debian' }}"

- name: Install stylua from GitHub releases
  unarchive:
    src: "https://github.com/JohnnyMorganz/StyLua/releases/download/v0.13.1/stylua-{{ 'macos' if ansible_facts['os_family'] == 'Darwin' else 'linux' }}.zip"
    dest: "~/.local/bin"
    mode: "u+x"
    remote_src: true
