export ZSH="$HOME/.oh-my-zsh"
ZSH_THEME="agnoster"
plugins=(git kubectl aws)

source $ZSH/oh-my-zsh.sh

# FZF keybindings and completion
_fzf_prefix="$(brew --prefix fzf)/shell"
[ -f "$_fzf_prefix/key-bindings.zsh" ] && source "$_fzf_prefix/key-bindings.zsh"
[ -f "$_fzf_prefix/completion.zsh" ] && source "$_fzf_prefix/completion.zsh"
unset _fzf_prefix

export PYENV_ROOT="$HOME/.pyenv"
[[ -d $PYENV_ROOT/bin ]] && export PATH="$PYENV_ROOT/bin:$PATH"
eval "$(pyenv init - zsh)"

source $HOME/.dotfiles/roles/zsh/functions.zsh
source $HOME/.dotfiles/roles/zsh/aliases.zsh
source $HOME/.dotfiles/roles/zsh/completion.zsh
source $HOME/.dotfiles/roles/zsh/config.zsh
source $HOME/.dotfiles/roles/zsh/env.zsh
source $HOME/.dotfiles/roles/zsh/path.zsh

if [ -f ~/.localrc ]; then
  source ~/.localrc
fi

fpath+=~/.zfunc
autoload -Uz compinit && compinit

# Created by `pipx` on 2025-09-05 03:25:21
export PATH="$PATH:$HOME/.local/bin"

# Added by Antigravity
export PATH="$HOME/.antigravity/antigravity/bin:$PATH"
