- name: Add golang plugin to asdf
  command: "asdf plugin-add golang"
  register: golang_add
  failed_when: golang_add == 2

- name: Install golang {{version}} with asdf
  command: "asdf install golang {{version}}"

- name: Set global version for golang to {{version}}
  command: "asdf global golang {{version}}"
