---
- include_tasks: mac.yml
  when: ansible_os_family == "Darwin"

- include_tasks: debian.yml
  when: ansible_os_family == "Debian"

- name: Install Python version from versions.yml
  shell: |
    export PATH="{{ ansible_env.HOME }}/.pyenv/bin:$PATH"
    eval "$(pyenv init -)"
    pyenv install {{ python_version }} --skip-existing
  register: pyenv_result
  changed_when: "'already installed' not in pyenv_result.stderr"

- name: Set global Python version
  shell: |
    export PATH="{{ ansible_env.HOME }}/.pyenv/bin:$PATH"
    eval "$(pyenv init -)"
    pyenv global {{ python_version }}
  changed_when: false


- name: Check if pytest.ini file exists
  stat:
    path: "{{ ansible_env.HOME }}/pytest.ini"
  register: pytest_stat

- name: Back up existing pytest.ini
  command: "mv {{ ansible_env.HOME }}/pytest.ini {{ ansible_env.HOME }}/pytest.ini.bak"
  args:
    creates: "{{ ansible_env.HOME }}/pytest.ini.bak"
  when: pytest_stat.stat.exists and not pytest_stat.stat.islnk

- name: Link pytest.ini file
  file:
    src: "{{ dotfiles_home }}/roles/python/files/pytest.ini"
    dest: "{{ ansible_env.HOME }}/pytest.ini"
    state: link
    force: yes
