- name: Install pyenv
  homebrew:
    name: pyenv
    state: present

- name: Get latest stable Python 3 version
  shell: pyenv install --list | grep -E '^\s+3\.[0-9]+\.[0-9]+$' | tail -1 | tr -d ' '
  register: python_latest
  changed_when: false

- name: Install latest Python 3
  shell: pyenv install {{ python_latest.stdout }} --skip-existing
  register: pyenv_result
  changed_when: "'already installed' not in pyenv_result.stderr"

- name: Set global Python version
  shell: pyenv global {{ python_latest.stdout }}
  changed_when: false

- name: Check if pytest.ini file exists
  stat:
    path: "{{ ansible_env.HOME }}/pytest.ini"
  register: pytest_stat

- name: Back up existing pytest.ini
  command: mv ~/pytest.ini ~/pytest.ini.bak
  args:
    creates: "{{ ansible_env.HOME }}/pytest.ini.bak"
  when: pytest_stat.stat.exists and not pytest_stat.stat.islnk

- name: Link pytest.ini file
  file:
    src: "{{ dotfiles_home }}/roles/python/files/pytest.ini"
    dest: "{{ ansible_env.HOME }}/pytest.ini"
    state: link
    force: yes

- name: Install pipx
  homebrew:
    name: pipx
    state: present
