---
- name: Check if Homebrew is installed
  shell: command -v brew
  register: homebrew_check
  failed_when: false
  changed_when: false

- name: Installing Homebrew
  shell: /bin/bash -c "$(curl -fsSL https://raw.githubusercontent.com/Homebrew/install/HEAD/install.sh)"
  when: homebrew_check.rc != 0 and ansible_os_family == "Darwin"

- include_tasks: update.yml
  when: homebrew_check.rc == 0 and ansible_os_family == "Darwin"
