---
- name: Check if Homebrew is installed
  shell: command -v brew
  register: homebrew_check
  failed_when: false
  changed_when: false

- name: Installing Homebrew
  shell: /bin/bash -c "$(curl -fsSL https://raw.githubusercontent.com/Homebrew/install/HEAD/install.sh)"
  when: homebrew_check.rc != 0

- name: Updating Homebrew
  homebrew:
    update_homebrew: true
  when: homebrew_check.rc == 0

- name: Upgrading Homebrew Packages
  homebrew:
    upgrade_all: true
  register: result
  until: result is successful
  when: homebrew_check.rc == 0
