---
- name: Install Git
  package:
    name: git
    state: present
  become: "{{ ansible_os_family != 'Darwin' }}"

- name: Link global gitignore file
  file:
    src: "{{ dotfiles_home }}/roles/git/files/gitignore_global.link"
    dest: "{{ dotfiles_user_home }}/.gitignore_global"
    state: link
    force: yes

- name: Check if gitconfig exists
  stat:
    path: "{{ dotfiles_user_home }}/.gitconfig"
  register: gitconfig_stat

- name: Back up gitconfig
  command: "mv {{ dotfiles_user_home }}/.gitconfig {{ dotfiles_user_home }}/.gitconfig.bak"
  args:
    creates: "{{ dotfiles_user_home }}/.gitconfig.bak"
  when: gitconfig_stat.stat.exists and not gitconfig_stat.stat.islnk

- name: Make sure gitconfig is up to date
  template:
    src: "gitconfig.j2"
    dest: "{{ dotfiles_user_home }}/.gitconfig"

- name: Deploy work gitconfig profile
  template:
    src: "gitconfig-work.j2"
    dest: "{{ dotfiles_user_home }}/.gitconfig-work"

- name: Ensure .ssh directory exists
  file:
    path: "{{ dotfiles_user_home }}/.ssh"
    state: directory
    mode: "0700"

- name: Check if SSH config exists
  stat:
    path: "{{ dotfiles_user_home }}/.ssh/config"
  register: sshconfig_stat

- name: Back up SSH config
  command: "mv {{ dotfiles_user_home }}/.ssh/config {{ dotfiles_user_home }}/.ssh/config.bak"
  args:
    creates: "{{ dotfiles_user_home }}/.ssh/config.bak"
  when: sshconfig_stat.stat.exists and not sshconfig_stat.stat.islnk

- name: Deploy SSH config
  template:
    src: "ssh_config.j2"
    dest: "{{ dotfiles_user_home }}/.ssh/config"
    mode: "0600"
  when: not (lookup('env', 'CI') | default(false, true))

- name: Generate SSH keys
  include_tasks: ssh_keys.yml
  when: not (lookup('env', 'CI') | default(false, true))
