- name: Install node
  homebrew:
    name: node
    state: present

- name: Install global npm packages
  npm:
    name: "{{ item }}"
    global: true
  loop:
    - yarn
    - n
    - diff-so-fancy
    - npm-merge-driver
    - "@tailwindcss/language-server"
