#!/bin/zsh
#
# This lets you quickly jump into a project directory.
#
# Type:
#
#   c <tab>
#
# ...to autocomplete on all of your projects in the directories specified in
# `functions/_c`. Typically I'm using it like:
#
#    c holm<tab>/bo<tab>
#
# ...to quickly jump into holman/boom, for example.

c() {
  if [[ -z "$1" ]]; then echo "Usage: c <project>" >&2; return 1; fi
  if [[ -z "$PROJECTS" ]]; then echo "PROJECTS not set" >&2; return 1; fi
  cd "$PROJECTS/$1" || return 1
}
