---
- name: Add Alacritty PPA
  apt_repository:
    repo: ppa:aslatter/ppa
    state: present
  become: true
  when: ansible_distribution == 'Ubuntu'

- name: Install Alacritty
  package:
    name: alacritty
    state: present
  become: true
