- include_tasks: mac.yml
  when: ansible_os_family == "Darwin"

- name: Install Claude Code (native)
  shell: curl -fsSL https://claude.ai/install.sh | bash
  register: claude_install_output

- name: Debug Claude installation output
  debug:
    var: claude_install_output.stdout_lines
